### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by dan-gamble** [tjadea/Portfolio#2]
Hey Tam,

Just came across this, looking really good! Where is your hosting at? The page loads are taking about a minute for me at the moment and wondering if i can help you speed it up

**Comment by tjadea** [comment]
Yeah my original hosting provider is just awful (it was only a reddit promoted thing) so im moving it to netlify (waiting on DNS update... and im curious about netlify) just to see if it helps. Originally I used github pages with the custom domain but have tried to stray from that.

**Comment by dan-gamble** [comment]
How comes you've strayed from that? It's what i was going to suggest myself.

Netlify is interesting, especially for a blog. It'll definitely help you with learning a frontend framework.

If you want any help with it feel free to give me a shout.

**Comment by tjadea** [comment]
Thank you!

Im just continually trying to learn in different areas. I don't want to stick to just one area or concept. I will probably use github pages again in the future depending on how things go but Netlify seems straightforward and clean too.

**Comment by dan-gamble** [comment]
If you've only just started i'd try and focus on one area. It's better to get really good at one thing then branch out from there. When you get really good at one area, it makes other areas a lot easier to learn.

What are you trying to focus on learning at the moment specifically? I imagine a lot of your Python background is making Javascript and the programming concepts quite easy to pick up.

**Comment by tjadea** [comment]
I want to get better at Javascript and general frameworks. I've followed various bootcamps, tasks, etc so I understand concept but want better execution of Javascript in general.

Frameworks are interesting. I'm looking at the whole React / Vue / etc concepts. Im also going to do a bit more practice with vanilla markups as I used Bootstrap 3 to begin with but then migrated to Bootstrap 4 anyway.

The more I learn and look at I know my initial markup in html / css is messy, but its something I am continually improving on also.

**Comment by tjadea** [comment]
Oh (not sure how to edit posts on mobile)!

Yeah concepts are easier to pick up on considering I know Python and Java from University (thankfully).

Just the general idea of 'what to make' with Javascript bothers me sometimes. I know what it is used for but I feel like I'm only using in finitely in its capacity.
